### ISSUE TITLE
CAST throws Syntax error 

### ISSUE THREAD

**Issue by danfrankj** [slaclab/lacquer#1]
Howdy - I just tried out lacquer and it seems like CAST causes an uninformative error to be thrown

```
In [44]: parser.parse("SELECT CAST(a AS BIGINT) FROM b")
  File "<string>", line 94
    SELECT CAST(a AS BIGINT) FROM b
          ^
SyntaxError: Syntax error
```

FYI @johnbodley

**Comment by brianv0** [comment]
I just noticed this issue. I didn't add support for cast just yet (its a special function with effectively an aliased expression, as opposed to just an expression), I'll work on that.

**Comment by brianv0** [comment]
I fixed this on master(meant to do a PR :/), so now the parse tree (in python) looks something like this:

```
>>> parser.parse("SELECT CAST(a AS BIGINT) FROM b").query_body.select
Select(distinct=False,
       select_items=[
           SingleColumn(expression=
                        Cast(expression=
                             QualifiedNameReference(name=QualifiedName(a)),
                             data_type='BIGINT',
                             safe=False)
                        )
       ])
```

I haven't added try_cast (It will be trivial but I want to read up on it) and timestamp casting will need more work for timezone support.

**Comment by brianv0** [comment]
On a related note: I don't have very good error handling yet.

**Comment by danfrankj** [comment]
Thank you!
