### ISSUE TITLE
COUNT(*)

### ISSUE THREAD

**Issue by danfrankj** [slaclab/lacquer#6]
SELECT COUNT(*) FROM foo 

currently fails as a syntax error

**Comment by brianv0** [comment]
Missing "set function specification" in grammar. I'll add it very soon.

**Comment by brianv0** [comment]
Fixed.

The implementation is consistent with presto in that it also parses `select foo(*) from bar` but omits the asterisk when formatting it, which is a bit weird, but that's probably okay.
