### ISSUE TITLE
publish to pypi

### ISSUE THREAD

**Issue by danfrankj** [slaclab/lacquer#9]
Would you be willing to publish this package to pypi so that it'll be easier to install ?

**Comment by brianv0** [comment]
Published to https://pypi.python.org/pypi/lacquer.

I'll bump the version for next development cycle.

**Comment by brianv0** [comment]
If you have issues with doing `pip install` etc... please let me know. I had no issues in a virtualenv, but I'd imagine if you have to do `sudo pip install` for your environment and then you try to use it, there may be some issues with how the tables are generated.
